### ISSUE TITLE
latest version is AuraRouter 3.0.0

### ISSUE THREAD

**Issue by othpiik** [zendframework/zend-expressive-aurarouter#10]
zend-expressive-aurarouter take AuraRouter 2.3.0 
how to upgrade latest version to AuraRouter 3.0.0, please?

**Comment by sandrokeil** [comment]
Are there BC breaks? You can try this in your composer.json `3.0.0 as 2.3.0`.

**Comment by geerteltink** [comment]
You can't just update to 3.0. Some used classes are gone or renamed. I guess a rewrite is needed, which might be easy since 3.x is made for PSR-7.

**Comment by geerteltink** [comment]
If you want you can test it: #11

**Comment by weierophinney** [comment]
Fixed with #11, which will release with a forthcoming 1.1.0.
